`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 16.03.2026 16:45:15
// Design Name: 
// Module Name: tb_radarnet
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

/*
 * tb_radarnet.v - Testbench for RadarNet-1D FPGA Accelerator
 * =============================================================
 * Generates a 100 MHz clock, loads test vectors from .hex files,
 * feeds them to radarnet_top, compares outputs against expected
 * labels, and reports pass/fail count and latency.
 *
 * Test vector files (generated by generate_tb_vectors.py):
 *   input_vectors.hex   - 50 × 128 entries of {I[7:0], Q[7:0]}
 *   expected_labels.hex - 50 entries of expected class_id (8-bit)
 *
 * Simulation:
 *   iverilog -o radarnet_sim rtl/*.v && vvp radarnet_sim
 *   Or use Vivado: xvlog *.v && xelab tb_radarnet && xsim tb_radarnet
 */

module tb_radarnet;

    // ── Parameters ──────────────────────────────────────────────────
    parameter CLK_PERIOD   = 10;     // 100 MHz -> 10 ns period
    parameter NUM_SAMPLES  = 128;    // I/Q samples per vector
    parameter NUM_VECTORS  = 50;     // total test vectors
    parameter NUM_CLASSES  = 4;
    parameter DATA_WIDTH   = 8;

    // ── Clock and Reset ─────────────────────────────────────────────
    reg clk;
    reg rst_n;

    initial begin
        clk = 1'b0;
        forever #(CLK_PERIOD / 2) clk = ~clk;
    end

    // ── DUT signals ─────────────────────────────────────────────────
    reg         start;
    reg         iq_valid;
    reg  [15:0] iq_data;
    wire        done;
    wire        busy;
    wire [1:0]  class_id;
    wire        anomaly_flag;
    wire        result_valid;
    wire [2:0]  fsm_state;
    wire [31:0] cycle_count;

    // ── DUT Instantiation ───────────────────────────────────────────
    radarnet_top #(
        .DATA_WIDTH(DATA_WIDTH),
        .NUM_SAMPLES(NUM_SAMPLES),
        .NUM_CLASSES(NUM_CLASSES)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .start(start),
        .done(done),
        .busy(busy),
        .iq_valid(iq_valid),
        .iq_data(iq_data),
        .class_id(class_id),
        .anomaly_flag(anomaly_flag),
        .result_valid(result_valid),
        .fsm_state(fsm_state),
        .cycle_count(cycle_count)
    );

    // ── Test Vector Memory ──────────────────────────────────────────
    reg [15:0] input_mem [0:NUM_VECTORS*NUM_SAMPLES-1];  // {I, Q} pairs
    reg [7:0]  label_mem [0:NUM_VECTORS-1];              // expected class

    initial begin
        $readmemh("input_vectors.hex", input_mem);
        $readmemh("expected_labels.hex", label_mem);
    end

    // ── Counters ────────────────────────────────────────────────────
    integer vec_idx;
    integer sample_idx;
    integer pass_count;
    integer fail_count;
    integer total_cycles;
    reg [1:0] expected_class;

    // ── Test Sequence ───────────────────────────────────────────────
    initial begin
        // Setup
        $dumpfile("radarnet_tb.vcd");
        $dumpvars(0, tb_radarnet);

        rst_n    = 1'b0;
        start    = 1'b0;
        iq_valid = 1'b0;
        iq_data  = 16'd0;
        pass_count = 0;
        fail_count = 0;
        total_cycles = 0;

        // Reset
        #(CLK_PERIOD * 5);
        rst_n = 1'b1;
        #(CLK_PERIOD * 2);

        $display("============================================");
        $display("  RadarNet-1D Testbench - %0d vectors", NUM_VECTORS);
        $display("============================================");
        $display("");

        // ── Process each test vector ────────────────────────────────
        for (vec_idx = 0; vec_idx < NUM_VECTORS; vec_idx = vec_idx + 1) begin
            expected_class = label_mem[vec_idx][1:0];

            // Pulse start
            @(posedge clk);
            start = 1'b1;
            @(posedge clk);
            start = 1'b0;

            // Wait for LOAD state
            @(posedge clk);

            // Feed 128 I/Q samples
            for (sample_idx = 0; sample_idx < NUM_SAMPLES;
                 sample_idx = sample_idx + 1) begin
                @(posedge clk);
                iq_valid = 1'b1;
                iq_data  = input_mem[vec_idx * NUM_SAMPLES + sample_idx];
            end
            @(posedge clk);
            iq_valid = 1'b0;
            iq_data  = 16'd0;

            // Wait for done
            wait (done == 1'b1);
            @(posedge clk);

            // Check result
            total_cycles = total_cycles + cycle_count;

            if (class_id == expected_class) begin
                pass_count = pass_count + 1;
                $display("  [PASS] Vector %3d: expected=%0d, got=%0d  "
                         ,"(anomaly=%b, cycles=%0d)",
                         vec_idx, expected_class, class_id,
                         anomaly_flag, cycle_count);
            end else begin
                fail_count = fail_count + 1;
                $display("  [FAIL] Vector %3d: expected=%0d, got=%0d  "
                         ,"(anomaly=%b, cycles=%0d)",
                         vec_idx, expected_class, class_id,
                         anomaly_flag, cycle_count);
            end

            // Small gap between vectors
            #(CLK_PERIOD * 5);
        end

        // ── Summary ─────────────────────────────────────────────────
        $display("");
        $display("============================================");
        $display("  RESULTS SUMMARY");
        $display("============================================");
        $display("  Total vectors : %0d", NUM_VECTORS);
        $display("  Passed        : %0d", pass_count);
        $display("  Failed        : %0d", fail_count);
        $display("  Accuracy      : %0d%%",
                 (pass_count * 100) / NUM_VECTORS);
        $display("  Avg latency   : %0d cycles (%0d ns @ 100MHz)",
                 total_cycles / NUM_VECTORS,
                 (total_cycles / NUM_VECTORS) * CLK_PERIOD);
        $display("============================================");

        if (fail_count == 0)
            $display("  *** ALL TESTS PASSED ***");
        else
            $display("  *** %0d TESTS FAILED ***", fail_count);

        $display("");
        $finish;
    end

    // ── Timeout watchdog ────────────────────────────────────────────
    initial begin
        #(CLK_PERIOD * 10_000_000);   // 100 ms timeout
        $display("ERROR: Simulation timed out!");
        $finish;
    end

endmodule